### ISSUE TITLE
debian bootstrap recipe fails, not clear reasons

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#109] opened 2018-02-26 21:11 UTC
## Link to Container Collection Log, Build, or Collection (in that order)

Here is a sample (I have 4 tags) log: https://www.singularity-hub.org/containers/1873/log to build from this recipe https://github.com/yarikoptic/vowpal_wabbit/blob/master/singularity/Singularity.debian-unstable-i386

### Behavior when Building Locally

It seems to build just fine locally using 

`sudo singularity build singularity-vw.img Singularity.debian-unstable-i386` 

using 2.4.2-dist version of singularity

### Error on Singularity Hub

```
Start Time: Mon Feb 26 20:55:33 UTC 2018.
Cloning into '/tmp/tmps3dxpg0t'...
ERROR Return Code 1: b"Enabling debugging
Ending argument loop
Singularity version: 2.4.1-feature-squashbuild-secbuild-2.4.1.g220f8e0
Exec'ing: /usr/local/libexec/singularity/cli/build.exec
Using container recipe deffile: /tmp/tmps3dxpg0t/singularity/Singularity.debian-unstable-i386
Building into existing container: /root/build
...
I: Unpacking the base system...
W: Failure while installing base packages. This will be re-attempted up to five times.
W: See /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log for details
W: Failure while installing base packages. This will be re-attempted up to five times.
W: See /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log for details
W: Failure while installing base packages. This will be re-attempted up to five times.
W: See /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log for details
W: Failure while installing base packages. This will be re-attempted up to five times.
W: See /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log for details
W: Failure while installing base packages. This will be re-attempted up to five times.
W: See /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log for details
\x1b[31mABORT: Aborting with RETVAL=255
...
```

### What do you think is going on?

https://www.youtube.com/watch?v=sVyRkl5qNb8

**Comment by vsoch** [comment] 2018-02-26 21:17
I think this comes down to needing a dependency on the host that singularity hub doesn't have in the secure build. @cclerget any insight to this, other than manually doing the build and viewing the log? I'm finding similar bugs like https://github.com/meefik/linuxdeploy/issues/555

**Comment by yarikoptic** [comment] 2018-03-01 13:38
@vsoch , thanks for pinging @cclerget .... but I wondered -- is there a way to get a hold of those /usr/local/var/singularity/mnt/container/debootstrap/debootstrap.log which might shine the light on the situation

**Comment by vsoch** [comment] 2018-03-01 13:41
I would have to catch the builder mid build, sneak in, and look at the log before the server is brought down. It also takes about 30 minutes to an hour to mimic the builder and manually bring up an instance to test. Given that a new builder will be made when Singularity is updated (soonish?) and the number of things on my todo queue, I would like to explore these other options first.

**Comment by vsoch** [comment] 2018-03-01 13:44
Ah but actually you can test this! If you install singularity (last release) and then run a secure build (with the --isolated flag) it should mimic what is going on (minus the extra bells and whistles). That might be worth trying in the meantime.

**Comment by yarikoptic** [comment] 2018-03-01 14:48
sure, no problem.  Actually, I could also probably just build them out of base docker images -- I think that might avoid the problem
isn't last release 2.4.2 which I have and which doesn't have --isolated for build?

**Comment by vsoch** [comment] 2018-03-01 14:51
We have isolated! Here is the routine to prepare the host: https://github.com/singularityware/singularity-python/blob/master/singularity/build/scripts/singularity-prepare-instance.sh#L52

**Comment by vsoch** [comment] 2018-03-01 14:52
And you know what they say, all roads lead (or come from) not Rome, but Docker layers!

**Comment by cclerget** [comment] 2018-03-01 15:07
@vsoch @yarikoptic Just reproduce error on my machine without and with  --isolated option, that's not related to secure build, I rebuild secure build image to use last ubuntu 18.04 (bionic): same errors. I run build under singularity 2.4.2-dist: same errors. Looks like a debootstrap bug, I have no idea why it works for you, maybe you patched debootstrap or you build on a i386 machine ? (I run builds on x86_64 machine)

Here the errors:

```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Selecting previously unselected package base-passwd.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack .../base-passwd_3.5.44_i386.deb ...
Unpacking base-passwd (3.5.44) ...
dpkg: base-passwd: dependency problems, but configuring anyway as you requested:
 base-passwd depends on libc6 (>= 2.8); however:
  Package libc6 is not installed.
 base-passwd depends on libdebconfclient0 (>= 0.145); however:
  Package libdebconfclient0 is not installed.

Setting up base-passwd (3.5.44) ...
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
Selecting previously unselected package base-files.
dpkg: regarding .../base-files_10.1_i386.deb containing base-files, pre-dependency problem:
 base-files pre-depends on awk
  awk is not installed.

dpkg: warning: ignoring pre-dependency problem!
(Reading database ... 41 files and directories currently installed.)
Preparing to unpack .../base-files_10.1_i386.deb ...
Unpacking base-files (10.1) ...
dpkg: base-files: dependency problems, but configuring anyway as you requested:
 base-files depends on awk; however:
  Package awk is not installed.

Setting up base-files (10.1) ...
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 51 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 51 package 'dpkg':
 missing architecture
dpkg: regarding .../dpkg_1.19.0.5_i386.deb containing dpkg, pre-dependency problem:
 dpkg pre-depends on libbz2-1.0
  libbz2-1.0 is not installed.
```

**Comment by vsoch** [comment] 2018-03-01 20:45
@yarikoptic can you try building the container with a docker debian base (not debootstrap?)

**Comment by vsoch** [comment] 2018-04-28 19:56
hey @yarikoptic ! 

I've just quietly added the new builder (with Singularity 2.5) as an option, and I think it would be worth a go to see if your container builds! To change your builder:

 - navigate to your Collection
 - click on "Settings"
 - under the Builder settings tag, change the cloud builder to `singularity-builder-2-5-100gb`

![image](https://user-images.githubusercontent.com/814322/39400175-4f814304-4af9-11e8-9f55-043ea9b45cd7.png)

And then commit and push again to trigger of course, and report back to me. Thank you!

**Comment by vsoch** [comment] 2019-07-01 21:03
@yarikoptic this issue is deprecated, given that the builder (still old) is over 2.4.1 (2.5.1). I'm going to close the issue, but I'd like you to please put any suggestions for future updates here -> https://forms.gle/sbb41gWtfLBvmm4k8 I am collecting feedback and preparing for another round of changes, so please get them in! :)

**Closed as completed by vsoch** 2019-07-01 21:03 UTC
Labels: bug

**Comment by yarikoptic** [comment] 2019-07-01 22:27
I already did ;-)

**Comment by vsoch** [comment] 2019-07-01 22:28
oooh then thank you kindly :0)
