### ISSUE TITLE
Cannot access collection settings page

### ISSUE THREAD

**Issue by ast0815** [singularityhub/singularityhub.github.io#231] opened 2021-01-16 11:58 UTC
### Links

 - container collection: https://singularity-hub.org/collections/5081
 - GitHub repository or recipe file: private

### Error on Singularity Hub

When I click on the "settings button", I get an error message "Beep Boop, Error!".
Also it does not seem to do any building when I push to the GitHub repo.

### What do you think is going on?

Something went wrong when I created the collection? The Browser was behaving a bit weird at that time.

**Comment by vsoch** [comment] 2021-01-16 18:07
hey @ast0815! It looks like when you created your collection there was some issue with authentication, so only half of the usual creation actions occurred (creating the collection) and not the final half (creating a builder for your collection). I've just manually done it, so you should be able to test looking at the collections page, and I'd also test the GitHub webhook again (because I do see it here). We would want to be able to track down the original  issue that was likely an error when you first authenticated or created the collection to get to the bottom, so if you are able to reproduce that let me know.

**Comment by ast0815** [comment] 2021-01-16 20:57
Thanks! It seems to work now. I don't remember doing anything out of the ordinary when I added the collection. I will let you know if it happens again.

**Comment by vsoch** [comment] 2021-01-16 21:39
Great! It probably was something like navigating away from the page before the server completed the response successfully. I'll close the issue here, and please reopen with details if you are able to reproduce.

**Closed as completed by vsoch** 2021-01-16 21:39 UTC
