### ISSUE TITLE
building problemns  on singularity hub.

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [singularityhub/singularityhub.github.io#134] opened 2018-06-01 08:49 UTC
I try to build my  singularity file on  ingularity 2.5-100GB on  singularity hub.

`bioinfo-dirty-jobs/oncotator_singularity`
I have an error on python..  If I use the 2.4 version it works..

**Comment by vsoch** [comment] 2018-06-01 10:53
I found your collection here --> https://singularity-hub.org/containers/3005 but I need to see an errored container / log / something to debug this.

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-01 11:12
@vsoch  Thanks so much for your help 
Isorry I'm  naive on singulairty hub.I have some problems on build with different tags..
here you have 
https://www.singularity-hub.org/containers/3005/log

**Comment by vsoch** [comment] 2018-06-01 11:20
Thank you! That's exactly what I need. The bug seems to be related to the extraction step, there is a whiteout file that likely is linked outside of the root filesystem:

```bash
Attempt to whiteout outside of rootfs /etc/python2.7/sitecustomize.py - aborting
```
I think you are hitting a bug addressed by this PR: https://github.com/singularityware/singularity/pull/1605 so the fix will come with the next release of Singularity, and if a previous version works for you in the meantime you can fall back to the 2.4.1 builder.@dctrud is this correct? @bioinfo-dirty-jobs if you are able to try this build locally with 2.5 to reproduce the error and then test @dctrud PR, this would be greatly helpful!

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-01 11:53
@vsoch  Localy seems work I was able to compile he image and use. In the hub I need 2.4

**Comment by vsoch** [comment] 2018-06-01 13:16
Show me the version of singularity?

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-01 13:25
@vsoch 
Sorry... here you have
```
$ singularity --version
2.5.1-release-2.5.g9170f65
```

**Comment by vsoch** [comment] 2018-06-01 13:30
Singularity Hub is using the squashfs build branch, could you please test by installing the secure build, and then adding the --isolated flag? The steps to install are shown here:

https://github.com/singularityware/singularity-python/blob/master/singularity/build/scripts/singularity-prepare-instance.sh#L55

and then build with `--isolated`

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-01 14:00
@vsoch I use centos7..

**Comment by vsoch** [comment] 2018-06-01 17:29
Just do the same cloning steps, but install dependencies with centos! (yum)

**Comment by vsoch** [comment] 2018-06-22 14:03
Any updates here?

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-22 14:10
I'm not able to install the new version...on my  centos.. I need to reintall al and see if there is some improve...

**Comment by vsoch** [comment] 2018-06-22 14:25
When do you plan to do this?

**Comment by bioinfo-dirty-jobs** [comment] 2018-06-22 14:34
Monday ...  still backup some data...I'll keep you n toouch monday afternon

**Comment by vsoch** [comment] 2018-06-22 14:37
Great! Thank you for the update :)

**Comment by vsoch** [comment] 2018-10-09 15:44
Ping @bioinfo-dirty-jobs any updates? Your .test container looks ok to me.

**Comment by bioinfo-dirty-jobs** [comment] 2018-10-09 15:51
Now works.. thanks so much

**Comment by vsoch** [comment] 2018-10-09 15:56
Great thanks! Closing issue.

**Closed as completed by vsoch** 2018-10-09 15:56 UTC
