### ISSUE TITLE
Build stuck in "Pending"

### ISSUE THREAD

**Issue by wsjeon** [singularityhub/singularityhub.github.io#169] opened 2019-06-29 18:07 UTC
## Link to Container Collection Log, Build, or Collection (in that order)
https://www.singularity-hub.org/collections/3083
https://www.singularity-hub.org/collections/3234

### Error on Singularity Hub
First I thought my singularity recipe could be wrong, but it works well when I build images in the local machine. So, I made a test recipe in another repository, but the same pending issue occurs.

**Comment by vsoch** [comment] 2019-06-29 18:21
These are public repositories? And how long does it take to build the recipe locally?

**Comment by vsoch** [comment] 2019-06-29 18:21
Could you please link me to the repository?

**Comment by baxpr** [comment] 2019-06-29 19:09
I'm having the same problem since yesterday:
https://www.singularity-hub.org/collections/3147
https://github.com/baxpr/fsthalconn

Recipe has taken a couple hours to build in the past. Trivial changes in the new version.

**Comment by wsjeon** [comment] 2019-06-29 19:15
@vsoch Thank you for the late reply. I make those repositories as public now. Links are

https://github.com/wsjeon/singularity-development-setting
https://github.com/wsjeon/marl-dev-setting

When I build my images in my local machine with VM, I thought it took at most 30 minutes.

Similar to @baxpr, my issues also happened starting from yesterday.

**Comment by vsoch** [comment] 2019-06-29 20:10
hey @wsjeon thanks for your patience! I just walked through debugging this with you, and it's nothing about your recipe - there is an issue with Google Compute for the zone it's running it. I can't give you an ETA since it's the weekend, but I've contacted Google Support and I'll give you an update as soon as possible! In the meantime, if you want a similar builder from GitHub, while I can't promise that the containers will be available after the testing period, the instance will be running until the end of next week, and you can test it here: https://containers.page/

**Comment by wsjeon** [comment] 2019-06-29 20:32
@vsoch I appreciate your help at the weekend. I'll try your recommendation. May I make my repositories as private again?

**Comment by vsoch** [comment] 2019-06-29 20:41
containers.page is a testing server, so it has been somewhat tested for public repos, but not for private. I would start with public, and if it works, then build a different private, and open an issue if needed. I don't expect it to work for private, just a heads up :)

**Comment by wsjeon** [comment] 2019-06-29 21:04
@vsoch I tried [https://containers.page/](https://containers.page/), but my container was queued and there was no progress.

![image](https://user-images.githubusercontent.com/20200538/60389483-bb024600-9a8f-11e9-9983-86a91bcff71f.png)

**Comment by vsoch** [comment] 2019-06-29 21:40
It looks like you've gone over the limit for triggering builds - they all failed. Please stop for now.

**Comment by vsoch** [comment] 2019-06-29 21:40
Your error message is "build timed out" so likely it's too long a build for this testing instance.

**Comment by wsjeon** [comment] 2019-06-30 03:30
Thanks. I decided to make my image in my local and use it until next week. I also made my repositories as private currently. I hope you to inform me if Google Compute issues are solved.

**Comment by vsoch** [comment] 2019-06-30 12:46
Good morning! Just a heads up that the builds failed because the default timeout is 10 minutes, see here https://cloud.google.com/cloud-build/docs/build-config#timeout_2. I'm going to edit this field to be longer and I'll let you know when we can try a build again.

**Comment by vsoch** [comment] 2019-06-30 13:03
hey @wsjeon can you send me a recipe from your repos that failed previously? I'm updating the server and I'd like to test myself with the same recipe.

**Comment by vsoch** [comment] 2019-06-30 15:35
hey @wsjeon the containers.page is updated so that it should work for a build that goes up to three hours (I just ran one that took 34 minutes). If you want to test your container there again, it would be worth a shot. I also added support for private repos, but I haven't tested that because I have a lot of other work to do today. I again tested Singularity Hub, specifically changing the zone of the builder that is having VM exhaustion, but this isn't possible to do because it goes outside of the zone of the hub instance itself. So all we can do is wait, and I'll keep working with Google to see what else can be done (I've never seen this kind of error before).

**Comment by wsjeon** [comment] 2019-06-30 16:23
Hi @vsoch, good morning. I made my git repo (https://github.com/wsjeon/marl-dev-setting) to public again, and the recipe I will use is "Singularity.zsh". I remove some part of my recipe that takes a long time. I'll try containers.page again.

**Comment by vsoch** [comment] 2019-06-30 16:33
okay I'm watching it - it looks like the first hook still had the repo as private (and that clone didn't work) but you pushed after that, and I'll watch those. Don't do any more pushes for now until I give you an update!

**Comment by vsoch** [comment] 2019-06-30 16:37
okay, so here is an issue - your test recipe is not valid. Let's take a look and I'll show you how to fix it. here is what you have:

```
# Header
Bootstrap: shub
From: docker://tensorflow/tensorflow:latest-gpu-py3
# From: wsjeon/singularity-development-setting:zsh
```
If you are pulling from a Singularity Hub image, it needs to look like this:

```
Bootstrap: shub
From: wsjeon/singularity-development-setting:zsh
```
But since we are testing shub we should use docker, so I'd suggest this:
```
Bootstrap: docker
From: tensorflow/tensorflow:latest-gpu-py3
```
Currently, the builder (with Singularity) is telling us that the recipe is not valid. 

![image](https://user-images.githubusercontent.com/814322/60399533-c8710c00-9b33-11e9-8626-a33f8467ef07.png)

But if you fix this up, it should get through the build :)

**Comment by vsoch** [comment] 2019-06-30 16:41
For your other recipe, I think the tag that you want is from this repo: https://www.singularity-hub.org/collections/3083

![image](https://user-images.githubusercontent.com/814322/60399564-46351780-9b34-11e9-8f8d-68f88f9807a6.png)

The other does not exist.

**Comment by vsoch** [comment] 2019-06-30 17:07
Great job! You fixed it up and have a green container :) https://containers.page/collections/41

```bash
$ singularity pull shub://containers.page/wsjeon/marl-dev-setting:zsh
```

**Comment by vsoch** [comment] 2019-06-30 17:07
Depending on your version of Singularity, you can also try pulling with the library endpoint:

```bash
$ singularity pull --library https://containers.page wsjeon/marl-dev-setting:zsh
```

**Comment by wsjeon** [comment] 2019-06-30 17:27
I tried 
```
$ singularity pull shub://containers.page/wsjeon/marl-dev-setting:zsh
```
and successfullly downloaded the file, but got the following error:
```
ERROR  : Unknown image format/type: wsjeon-marl-dev-setting-wsjeon-marl-dev-setting-zsh.simg
ABORT  : Retval = 255
```
I also tried
```
singularity pull --library https://containers.page wsjeon/marl-dev-setting:zsh
```
, but it doesn't work for me.

**Comment by vsoch** [comment] 2019-06-30 17:28
What is your version of Singularity?

**Comment by wsjeon** [comment] 2019-06-30 17:30
```
$ singularity --version
2.6.1-dist
```

**Comment by vsoch** [comment] 2019-06-30 17:31
Ah, so containers.page is building 3.2.1, so the image format is squashfs (SIF). Singularity Hub is still building 2.5.1. Are you able to update your version of Singularity?

**Comment by wsjeon** [comment] 2019-06-30 17:32
Sorry, I can't because I run singularity on the server.

**Comment by dmitriy-serdyuk** [comment] 2019-06-30 17:35
It seems that I have a similar issue with my container: https://www.singularity-hub.org/collections/3219 'Pending' for almost two days already.

**Comment by vsoch** [comment] 2019-06-30 17:37
@dmitriy-serdyuk it's out of my hands - the VMs are exhausted for the zone that I'm in, and I'm unable to ask for a zone different from where the server is running. I'm (actively) working with Google for them to make some change on the backend (and then me to test again) but aside from that, there isn't much I can do. I apologize for the pause in service - I'm the only engineer running this so it's all on me.

**Comment by dmitriy-serdyuk** [comment] 2019-06-30 17:40
@vsoch thanks for the heads up!

**Comment by vsoch** [comment] 2019-06-30 17:43
Sure thing! I'm getting user feedback now, and also talking with Google, but I'm thinking it's about time for an update to the server. Either I would want to update Singularity Hub (current) to allow for building newer versions of Singularity (this would require help from Sylabs, as they have not provided a secure build since 2.5.1) or convert the entirely of Singularity Hub into a Singularity Registry Server, and use Google Cloud Build instead of the custom queue / instances that I created now years ago. There is too much uncertainty to know for sure what might be possible, and it also counts on Google's continued support. If Google can't support, then there isn't much left to do. If Sylabs won't help with a secure build, then the first option isn't an option. So... we can only wait and see how things unfold.

**Comment by wsjeon** [comment] 2019-06-30 21:37
@vsoch I tried [Singularity Builders Travis CI for release 2.6](https://github.com/singularityhub/travis-ci/tree/release/2.6) and built my image on Singularity 2.6 successfully.

Now I try to upload my image to my google drive, and I think I can do it manually.
FYI, I leave [the link](https://github.com/wsjeon/travis-ci/tree/release/2.6). 

Is there a good way to upload my images directly to my google drive or dropbox?

**Comment by vsoch** [comment] 2019-06-30 21:51
Yes! Singularity Registry Client has endpoints for both Dropbox and Google Drive, so you should start with the instructions [here](https://singularityhub.github.io/sregistry-cli/clients) to choose your client, and then add any needed environment variables to the travis build. Once your travis build has the environment variables, as it's shown in the [instructions](https://github.com/wsjeon/travis-ci/tree/release/2.6#quick-start) you would issue a build command with sregistry to target your client of choice. If you have issues, please open them in the travis repository and we can walk through them together.

Heads up I need to go for a run / make dinner, so I might be afk.

**Comment by vsoch** [comment] 2019-06-30 21:52
As you are doing this, please write down every step / link to what you are working on so if/when an error arises, it will be easy to share with me without needing to go back and remember.

**Comment by vsoch** [comment] 2019-07-01 15:02
hey @wsjeon ! No promises that this is completely working yet, however I've done extensive server work (to discover machine types and zones that *are* available) and just tested your container to build, and it ran and seemed to build successfully -> https://www.singularity-hub.org/collections/3234.

**Comment by baxpr** [comment] 2019-07-01 15:50
Mine is running now :)

**Comment by vsoch** [comment] 2019-07-01 15:50
I know, I'm watching it as we speak :)

**Comment by vsoch** [comment] 2019-07-01 15:51
![image](https://user-images.githubusercontent.com/814322/60449844-86f56500-9bf6-11e9-9427-b68955e367a0.png)

**Comment by vsoch** [comment] 2019-07-01 16:50
@wsjeon when you've had a chance to test, let me know if things are working on on your end. When confirmed, we can close the issue.

**Comment by wsjeon** [comment] 2019-07-01 18:42
@vsoch Thanks! It's working now. I really appreciate your help!

**Closed as completed** 2019-07-01 18:42 UTC
