### ISSUE TITLE
Manage collections that are part of an organization

### ISSUE THREAD

**Issue by octomike** [singularityhub/singularityhub.github.io#136] opened 2018-06-12 09:34 UTC
### Error on Singularity Hub

Currently only one person of our organization can activate a collection and then manage it (freeze, delete, build, ..). Whenever a second person tries to activate a collection we get a beep boop.

### What do you think is going on?

Collections are bound to a single user, when in fact they should be bound to a set of users in the case of an organization.

**Comment by vsoch** [comment] 2018-06-12 12:12
hey @octomike ! The reason for this is because ownership (and who controls the webhooks,etc) is tied to one individual (not institution or organization) account. I think this will likely change if/when the next version of shub is released (note that Singularity Registry has teams and this would be a component) but for a quick fix, I don't see the need as dire. I do think that there shouldn't be a server error - minimally some kind of transaction to transfer a repo between users should be possible! Are you able to give me more detail to one of these errors so I can track it / reproduce it on my end, and test how to better deal with it?

**Comment by octomike** [comment] 2018-06-12 12:22
hey @vsoch 

> minimally some kind of transaction to transfer a repo between users should be possible!

Yes, that would be great.

> Are you able to give me more detail to one of these errors so I can track it / reproduce it on my end, and test how to better deal with it?

I'm not sure what you need. The POST request just spits out a 500. I just (Tue, 12 Jun 2018 12:18:55 GMT) tested this by trying to activate the repo MPIB/singularity-mrtrix3 on singularity-hub.org. Does that help at all?

**Comment by vsoch** [comment] 2018-06-12 17:39
Yes I found it!

The underlying server error is a database integrity error, because the unique ID of the repo was already found (and creating a new collection for it violates a unique rule, as it should!) What I could do here is catch the error, and then redirect the user to some settings page to transfer ownership. The owner would need to type in the Github repo of the other user, and then I'd need to check if the second user has permission , etc. and then do the switch. Do you see any issue with this approach? The second used could also be added as a sort of collaborator on the repo, which gives some editing rights (but still limited to the permissions they have in Github).

**Comment by octomike** [comment] 2018-06-14 09:36
Sounds good to me :+1:

**Comment by d-w-moore** [comment] 2018-07-18 15:14
A question at this point, possibly related: If an organization exists as an entity on GitHub, can it register a repository / collection / container / etc on Singularity-hub  namespaced for the entire organization? I mean, as opposed to having to register under the same names and/or linked accounts particular to the individual users in that organization.

**Comment by vsoch** [comment] 2018-07-18 15:21
Yes that is entirely possible. If you:

 - are a member of the organization with admin (write) priviledges
 - have given Singularity Hub access to the organization repos (under settings --> OAuth apps)
 - select the organization's repository (and not your user fork, or something like that).

It will show up under the organization name. As an example, take a look at the "singularityhub" namespace of containers on there --> https://singularity-hub.org/collections/57 I created these of course, but it's not my username "vsoch."

The **control** of building the containers still belongs to the user that connected the repository - what Singularity Hub doesn't do is any custom magic to extend permissions for a repository to a bunch of others (that likely don't have accounts on here). The suggested approach is to manage the containers for the organization as you normally would (commit / PR on Github with your organization) and then when there is a merge / deploy etc the resulting container (that many have worked on) will be built on Singularity Hub.

**Comment by d-w-moore** [comment] 2018-07-18 19:23
Vanessa,
Thanks for the very prompt and helpful response. I should probably have asked also about the implications of the second bullet point  -- concerning opening access to other organizations, honourable as their intentions certainly are, to our org's repos.  My management had previously seen that and had reservations. Being a new employee I don't have write access to the GitHub repository in question, but had written a container and wanted to migrate it to that namespace. Probably there's a workaround or two I can explore.
Thanks again! Best regards, - Dan

**Comment by vsoch** [comment] 2018-07-18 19:27
Singularity Hub doesn't do anything special with respect to changing permissions, it honors the GitHub permissions that are defined for users and their organizations, so if you have some issue with your repositories versus an organization the fix is to be done there. if you don't have write access to repository then you shouldn't have access to control it on Singularity Hub either, and you can contact someone with administrative privileges and your organization to discuss this. It isn't All or Nothing, privileges can be granted on the level of a repository for a user in an organization, and this would be my suggestion.

**Comment by vsoch** [comment] 2018-10-09 01:41
This is more of a question about organizations on Shub, which map to Github organizations. Closing issue, please let me know if there are further questions, thanks!

**Closed as completed by vsoch** 2018-10-09 01:41 UTC

**Comment by octomike** [comment] 2018-10-09 07:45
Hey Vanessa. This issue is still a big problem I'm afraid..

Collections that are part of an organization are still tied to a single individual on github and can only be controlled by that one person. Instead every member of the repos's team should be able to manage the collection.

**Comment by vsoch** [comment] 2018-10-09 10:02
hey @octomike! In terms of managing the content, you should do that through Github, and the user that connected the repository is in charge of administrative actions on Singularity Hub. I apologize for the trouble but this is the way that singularity hub works I encourage you to contribute to Singularity Registry Server to add a builder / connection to Github, as Singularity Register does have this missing feature, and if/when it's ever suitable to replace the current server you will get it for sure! :)

**Comment by Aneoshun** [comment] 2020-06-17 16:17
Hi @vsoch, 
I am running into the same problem. I have an organisation for my research group, and I want the members of my lab to put their code on github and use Shub to host the final image of their papers. However, I would like to also have access to their collections on shub, for instance to maintain them after they leave the lab.  Now that SRegistry has teams (and bots), do you see a different way to handle this issue?

**Comment by vsoch** [comment] 2020-06-17 16:47
Singularity Registry server is similar in some respects, but it's an entirely different tool, so adding teams wouldn't be an easy copy paste thing, and further, it would complicate trying to do it alongside GitHub permissions. I am hugely averse to changing the model that would need to do a migration on the database, because I absolutely cannot afford to lose it, so I don't see wanting to change the Collection model. What I can offer, however, is for you to submit a request with collections and previous users, and then the username to transfer them to (and cc previous owners so they will give their permission). If the permissions are okay for the organization, then the web hooks should still work (but I have never tried this so I'm not 100%).

**Comment by Aneoshun** [comment] 2020-06-17 16:51
Alright! Thanks for letting me know. I totally understand. 

Given that we only have a single project, probably the easier would be to delete the collection on my student's Shub account and recreate it on my Shub account. In the future, I will make sure to be the one creating the collections. Do you see a potential risk in doing this?

**Comment by vsoch** [comment] 2020-06-17 16:54
The only risk is that you would delete the previously built containers, and need to re-build on your account. I'd be happy to make the change for you on the server, in the case that you have containers already, it would save extra builds (each of which we pay for).

**Comment by Aneoshun** [comment] 2020-06-17 16:56
Ahh I haven't thought about this. Where/how do you want me to submit the request with the info?

**Comment by vsoch** [comment] 2020-06-17 17:00
I'll send you an email!

**Comment by Aneoshun** [comment] 2020-06-17 17:01
Thanks!
