### ISSUE TITLE
branches not being detected (debug needed)

### ISSUE THREAD

**Issue by sbilge** [singularityhub/singularityhub.github.io#190] opened 2019-10-07 20:52 UTC
### Link to Container Collection 
https://singularity-hub.org/collections/1457

### Behavior when Building Locally
I haven't built the images locally. 

### Error on Singularity Hub
Singularity Hub is not recognising my new branch of my existing collection. When I try to add a new collection, I do get a blank Singularity Hub page. 

My GitHub commits are failing to trigger build. I checked the Webhooks on my GitHub repository. According to the logs, the response to the POST request is "Invalid HTTP Response: 301". 

I am not sure what is going on.

**Comment by vsoch** [comment] 2019-10-07 21:04
The 301 is because of a redirect, and there has been quite a bit of communication about this. Instructions for fixing are here:

https://singularityhub.github.io/singularityhub-docs/2019/open-for-building/#webhooks

If you want to build from a new branch, you need to enable it in your collection settings. It won't just build without you doing that.

Note that this is a repeat of https://github.com/singularityhub/singularityhub.github.io/issues/189 - see there for even more information (I don't want to type it all again).

**Comment by sbilge** [comment] 2019-10-07 22:23
@vsoch thank you

**Comment by sbilge** [comment] 2019-10-07 22:48
@vsoch Webhooks work now. There is another issue, though. I reopened the issue for a reason :) In collection -> settings -> build branch settings I only see two branches, third one is missing. Is there a limitation on branch number?

**Comment by vsoch** [comment] 2019-10-07 22:57
Sorry - you had reopened and then no activity for 15 minutes so I assumed it was in error!

You are allowed as many branches as you like, so likely there is some issue with retrieving them. For now please just use master branch until I get a chance to take a look.

**Comment by sbilge** [comment] 2019-10-07 23:05
Thank you. The other problem is getting a blank page when clicked on "add a collection". I attached  the screen shot of the page that I got when I tried to add a new collection. 
<img width="1426" alt="Screenshot 2019-10-08 at 01 02 06" src="https://user-images.githubusercontent.com/19675834/66355428-96a7e680-e967-11e9-9f79-f17735bbaf1c.png">

**Comment by vsoch** [comment] 2019-10-07 23:09
Try disconnecting GitHub and reconnecting - this seems like an issue with your user token if you can't see any branches or collections.

**Comment by sbilge** [comment] 2019-10-07 23:14
Sorry, it did not help.
I realised something weird. In my other collection from an organisation GitHub repository, I only have one branch which is master. But, in the build branch settings, there are three branches, two of them does not belong to us. I checked GitHub twice.

**Comment by vsoch** [comment] 2019-10-07 23:26
Please show me the collection, and link on GitHub?

**Comment by vsoch** [comment] 2019-10-07 23:29
The branches I see are:

![image](https://user-images.githubusercontent.com/814322/66356361-84a25580-e91f-11e9-9dfc-41d58fd7bfa2.png)

Which I see one of in the linked repository - feature is missing only.

![image](https://user-images.githubusercontent.com/814322/66356383-9be14300-e91f-11e9-8b47-92ddc31773c4.png)

I don't understand your issue - there are no extra branches there.

**Comment by sbilge** [comment] 2019-10-07 23:30
Not detecting brach collection: https://singularity-hub.org/collections/1457 
Its GitHub: https://github.com/sbilge/ClinVAP

Collection with alien branches: https://singularity-hub.org/collections/2168
Its GitHub page: https://github.com/PersonalizedOncology/ClinVAP

**Comment by vsoch** [comment] 2019-10-07 23:35
Huh, you shouldn't have been able to add a repository id that already existed (the fork of an already added repo would have the same id), so I think this must be some edge case that resulted in bugs. If I were you I'd delete all collections, your account, and try reconnecting and then adding repos, one at a time.

**Comment by sbilge** [comment] 2019-10-07 23:48
I am a little hesitant to do it, since my paper (in revision) depends on those images and repositories. So I must ask: Do you see by any chance any other solution?

**Comment by vsoch** [comment] 2019-10-07 23:48
I'll look into this further tomorrow - going to take a bit of digging, and it's late here!

**Comment by vsoch** [comment] 2019-10-07 23:49
Yes I will debug this fully tomorrow - please don't do that yet :)

**Comment by sbilge** [comment] 2019-10-07 23:49
Thank you :)

**Comment by vsoch** [comment] 2019-10-08 13:47
Okay! We have some answers!

For collection 1457 - the issue was that your token isn't authenticating. This is likely because you haven't logged in since Singularity Hub was originally deployed, and a few months ago I revoked all tokens when I was worried about malicious use (there was no issue in the end). When I did the request without your token, the correct branches returned. I updated this for you when I was debugging so you should see all of them now. 

The larger issue behind the above was that, although you had authenticated again (with private) and that token _is_ working, there was a bug in the function so it was only using the first (non working) token. I fixed that if you want to test it, although I've already updated the branches for you.

For your other collection, the issue was also with the token - I can't say how or why you had the wrong branches, but I've fixed to only have master.

In all cases, the fix was trying both tokens. If you think the original (first account) _should_ work it's likely an issue that the token is expired, and what I can do is try refreshing it for you. Let me know.

**Comment by sbilge** [comment] 2019-10-08 14:40
Thank you very very very much!
For collection 1457, I triggered a build from branch "feature" and it seems like working. I haven't tested the collection 2168 yet.

**Comment by vsoch** [comment] 2019-10-08 14:45
Great! When you are happy that things are resolved, feel free to close the issue.

**Comment by vsoch** [comment] 2020-08-21 17:42
hey @sbilge it looks like this was resolved, so I'm closing the issue.  There was an issue that if you have many branches, the request wasn't paginated, so you could possibly not see branches. I'm not sure if that's related, but since you haven't pinged for ~10 months I'm going to guess the issue is resolved.

**Closed as completed by vsoch** 2020-08-21 17:42 UTC
