### ISSUE TITLE
Selected branch is ignored

### ISSUE THREAD

**Issue by patrickvdb** [singularityhub/singularityhub.github.io#90] opened 2017-11-21 12:44 UTC
## Link to Container Collection Log, Build, or Collection (in that order)
[https://www.singularity-hub.org/collections/276]()

[https://github.com/patrickvdb/multiqc-singularity/]()

### Behavior when Building Locally

works

### Error on Singularity Hub
Contradictive branches
![screen shot 2017-11-21 at 13 43 02](https://user-images.githubusercontent.com/6596512/33073061-ee3d681a-cec1-11e7-83bb-b251ecdeefd2.png)
![screen shot 2017-11-21 at 13 42 56](https://user-images.githubusercontent.com/6596512/33073062-ee5431f8-cec1-11e7-8d07-38ae3e1cd359.png)

### What do you think is going on?
No idea.

I link a specific branch ('v1.3') but Singularity ignores it and build the branch 'master'. After the build, it changes the 'branch' column (above) to 'master' even though I unselected the master branch in the settings
I will merge the two branches for now.

**Comment by vsoch** [comment] 2017-11-21 18:39
yes this definitely looks like a bug! The branch parsing comes from the webhook, so likely we should look there first. If you are able, can you go into your repository settings under Webhooks and send me the payload that was sent to the server? I should be able to debug and figure out from there!

**Comment by iosonofabio** [comment] 2017-11-21 19:47
Hi, I am running into the same problem, branches worked on the old version so this is a regression...

here the payload from the latest commit of my branch `stampy` of repo `organic-bo-factory` (https://github.com/iosonofabio/organic-box-factory/tree/stampy):

```
{
  "ref": "refs/heads/stampy",
  "before": "e66cea76fcafcb5a3beb30d35ed5c7b3a02b511b",
  "after": "3c21aa5596448a4647e0e0396dba4768482a9002",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/iosonofabio/organic-box-factory/compare/e66cea76fcaf...3c21aa559644",
  "commits": [
    {
      "id": "3c21aa5596448a4647e0e0396dba4768482a9002",
      "tree_id": "5de83bb62dfab3440c115451d3d17eae0f198bdd",
      "distinct": true,
      "message": "Works locally",
      "timestamp": "2017-11-21T11:45:31-08:00",
      "url": "https://github.com/iosonofabio/organic-box-factory/commit/3c21aa5596448a4647e0e0396dba4768482a9002",
      "author": {
        "name": "Fabio Zanini",
        "email": "fabio.zanini@fastmail.fm",
        "username": "iosonofabio"
      },
      "committer": {
        "name": "Fabio Zanini",
        "email": "fabio.zanini@fastmail.fm",
        "username": "iosonofabio"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "Singularity",
        "configure_image.sh"
      ]
    }
  ],
  "head_commit": {
    "id": "3c21aa5596448a4647e0e0396dba4768482a9002",
    "tree_id": "5de83bb62dfab3440c115451d3d17eae0f198bdd",
    "distinct": true,
    "message": "Works locally",
    "timestamp": "2017-11-21T11:45:31-08:00",
    "url": "https://github.com/iosonofabio/organic-box-factory/commit/3c21aa5596448a4647e0e0396dba4768482a9002",
    "author": {
      "name": "Fabio Zanini",
      "email": "fabio.zanini@fastmail.fm",
      "username": "iosonofabio"
    },
    "committer": {
      "name": "Fabio Zanini",
      "email": "fabio.zanini@fastmail.fm",
      "username": "iosonofabio"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "Singularity",
      "configure_image.sh"
    ]
  },
  "repository": {
    "id": 90328735,
    "name": "organic-box-factory",
    "full_name": "iosonofabio/organic-box-factory",
    "owner": {
      "name": "iosonofabio",
      "email": "fabio.zanini@fastmail.fm",
      "login": "iosonofabio",
      "id": 1200640,
      "avatar_url": "https://avatars2.githubusercontent.com/u/1200640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iosonofabio",
      "html_url": "https://github.com/iosonofabio",
      "followers_url": "https://api.github.com/users/iosonofabio/followers",
      "following_url": "https://api.github.com/users/iosonofabio/following{/other_user}",
      "gists_url": "https://api.github.com/users/iosonofabio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iosonofabio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iosonofabio/subscriptions",
      "organizations_url": "https://api.github.com/users/iosonofabio/orgs",
      "repos_url": "https://api.github.com/users/iosonofabio/repos",
      "events_url": "https://api.github.com/users/iosonofabio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iosonofabio/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/iosonofabio/organic-box-factory",
    "description": "Docker/Singularity containers for high-throughput sequencing pipelines in the cloud and on the ground",
    "fork": false,
    "url": "https://github.com/iosonofabio/organic-box-factory",
    "forks_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/forks",
    "keys_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/teams",
    "hooks_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/hooks",
    "issue_events_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/issues/events{/number}",
    "events_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/events",
    "assignees_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/assignees{/user}",
    "branches_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/branches{/branch}",
    "tags_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/tags",
    "blobs_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/languages",
    "stargazers_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/stargazers",
    "contributors_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/contributors",
    "subscribers_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/subscribers",
    "subscription_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/subscription",
    "commits_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/contents/{+path}",
    "compare_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/merges",
    "archive_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/downloads",
    "issues_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/issues{/number}",
    "pulls_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/labels{/name}",
    "releases_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/releases{/id}",
    "deployments_url": "https://api.github.com/repos/iosonofabio/organic-box-factory/deployments",
    "created_at": 1493951106,
    "updated_at": "2017-05-14T04:37:59Z",
    "pushed_at": 1511293539,
    "git_url": "git://github.com/iosonofabio/organic-box-factory.git",
    "ssh_url": "git@github.com:iosonofabio/organic-box-factory.git",
    "clone_url": "https://github.com/iosonofabio/organic-box-factory.git",
    "svn_url": "https://github.com/iosonofabio/organic-box-factory",
    "homepage": "",
    "size": 734175,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Shell",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 2,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 2,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "iosonofabio",
    "email": "fabio.zanini@fastmail.fm"
  },
  "sender": {
    "login": "iosonofabio",
    "id": 1200640,
    "avatar_url": "https://avatars2.githubusercontent.com/u/1200640?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/iosonofabio",
    "html_url": "https://github.com/iosonofabio",
    "followers_url": "https://api.github.com/users/iosonofabio/followers",
    "following_url": "https://api.github.com/users/iosonofabio/following{/other_user}",
    "gists_url": "https://api.github.com/users/iosonofabio/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/iosonofabio/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/iosonofabio/subscriptions",
    "organizations_url": "https://api.github.com/users/iosonofabio/orgs",
    "repos_url": "https://api.github.com/users/iosonofabio/repos",
    "events_url": "https://api.github.com/users/iosonofabio/events{/privacy}",
    "received_events_url": "https://api.github.com/users/iosonofabio/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

The response was: "Hook received, parsing" so it sounds good but nothing happens...

**Comment by patrickvdb** [comment] 2017-11-21 19:56
Payload
```
{
  "ref": "refs/heads/v1.3",
  "before": "768458431cd1dac4486b5db93e82080a24f89d04",
  "after": "50202ca9b4008ffb594c32a2846afbde18663c0a",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/patrickvdb/multiqc-singularity/compare/768458431cd1...50202ca9b400",
  "commits": [
    {
      "id": "50202ca9b4008ffb594c32a2846afbde18663c0a",
      "tree_id": "1550205084174f61293151464b590e112e0de9cc",
      "distinct": true,
      "message": "switch to personal docker",
      "timestamp": "2017-11-21T13:09:00+01:00",
      "url": "https://github.com/patrickvdb/multiqc-singularity/commit/50202ca9b4008ffb594c32a2846afbde18663c0a",
      "author": {
        "name": "Patrick van den Berg",
        "email": "pvdberg@physics.leidenuniv.nl"
      },
      "committer": {
        "name": "Patrick van den Berg",
        "email": "pvdberg@physics.leidenuniv.nl"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "Singularity"
      ]
    }
  ],
  "head_commit": {
    "id": "50202ca9b4008ffb594c32a2846afbde18663c0a",
    "tree_id": "1550205084174f61293151464b590e112e0de9cc",
    "distinct": true,
    "message": "switch to personal docker",
    "timestamp": "2017-11-21T13:09:00+01:00",
    "url": "https://github.com/patrickvdb/multiqc-singularity/commit/50202ca9b4008ffb594c32a2846afbde18663c0a",
    "author": {
      "name": "Patrick van den Berg",
      "email": "pvdberg@physics.leidenuniv.nl"
    },
    "committer": {
      "name": "Patrick van den Berg",
      "email": "pvdberg@physics.leidenuniv.nl"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "Singularity"
    ]
  },
  "repository": {
    "id": 97600730,
    "name": "multiqc-singularity",
    "full_name": "patrickvdb/multiqc-singularity",
    "owner": {
      "name": "patrickvdb",
      "email": "pvdb.90@gmail.com",
      "login": "patrickvdb",
      "id": 6596512,
      "avatar_url": "https://avatars2.githubusercontent.com/u/6596512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/patrickvdb",
      "html_url": "https://github.com/patrickvdb",
      "followers_url": "https://api.github.com/users/patrickvdb/followers",
      "following_url": "https://api.github.com/users/patrickvdb/following{/other_user}",
      "gists_url": "https://api.github.com/users/patrickvdb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/patrickvdb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/patrickvdb/subscriptions",
      "organizations_url": "https://api.github.com/users/patrickvdb/orgs",
      "repos_url": "https://api.github.com/users/patrickvdb/repos",
      "events_url": "https://api.github.com/users/patrickvdb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/patrickvdb/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/patrickvdb/multiqc-singularity",
    "description": null,
    "fork": false,
    "url": "https://github.com/patrickvdb/multiqc-singularity",
    "forks_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/forks",
    "keys_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/teams",
    "hooks_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/hooks",
    "issue_events_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/issues/events{/number}",
    "events_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/events",
    "assignees_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/assignees{/user}",
    "branches_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/branches{/branch}",
    "tags_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/tags",
    "blobs_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/languages",
    "stargazers_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/stargazers",
    "contributors_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/contributors",
    "subscribers_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/subscribers",
    "subscription_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/subscription",
    "commits_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/contents/{+path}",
    "compare_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/merges",
    "archive_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/downloads",
    "issues_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/issues{/number}",
    "pulls_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/labels{/name}",
    "releases_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/releases{/id}",
    "deployments_url": "https://api.github.com/repos/patrickvdb/multiqc-singularity/deployments",
    "created_at": 1500384056,
    "updated_at": "2017-07-18T13:20:56Z",
    "pushed_at": 1511266146,
    "git_url": "git://github.com/patrickvdb/multiqc-singularity.git",
    "ssh_url": "git@github.com:patrickvdb/multiqc-singularity.git",
    "clone_url": "https://github.com/patrickvdb/multiqc-singularity.git",
    "svn_url": "https://github.com/patrickvdb/multiqc-singularity",
    "homepage": null,
    "size": 2,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "patrickvdb",
    "email": "pvdb.90@gmail.com"
  },
  "sender": {
    "login": "patrickvdb",
    "id": 6596512,
    "avatar_url": "https://avatars2.githubusercontent.com/u/6596512?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/patrickvdb",
    "html_url": "https://github.com/patrickvdb",
    "followers_url": "https://api.github.com/users/patrickvdb/followers",
    "following_url": "https://api.github.com/users/patrickvdb/following{/other_user}",
    "gists_url": "https://api.github.com/users/patrickvdb/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/patrickvdb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/patrickvdb/subscriptions",
    "organizations_url": "https://api.github.com/users/patrickvdb/orgs",
    "repos_url": "https://api.github.com/users/patrickvdb/repos",
    "events_url": "https://api.github.com/users/patrickvdb/events{/privacy}",
    "received_events_url": "https://api.github.com/users/patrickvdb/received_events",
    "type": "User",
    "site_admin": false
  }
}

```
Response:
```
{"status": "Received", "message": "Hook received and parsing."}
```

**Comment by vsoch** [comment] 2017-11-21 20:14
Thanks guys this is perfect! I will look into soon. Happy :turkey: week!

**Comment by vsoch** [comment] 2017-11-21 20:44
okay first debugging stuffs - I walked through the webhook receive and can confirm the branch is passed to the builder:

![image](https://user-images.githubusercontent.com/814322/33095753-9ee58f02-ceb9-11e7-8478-53aa22d4e62d.png)

**Comment by vsoch** [comment] 2017-11-21 20:53
2. builder is receiving and parsing the params with branch included

```
{'branch': 'v1.3', 
'repo_id': '97600730', 
 'logfile': '/tmp/.shub-log', 
 'version': '17c701be46520a2c26f050f9d34a6629', 
 'tag': 'latest', 
 'bucket_name': 'singularityhub', 
'spec_file': 'Singularity',
 'commit': 'c1f01c03a52bffd279a10d1d1e8927ddf0f51b16',...
'container_id': '900'}
```

**Comment by vsoch** [comment] 2017-11-21 20:54
Singularity Hub gets the payload with correct branch:

```
res['branch']
['v1.3']
```

**Comment by vsoch** [comment] 2017-11-21 20:55
hmm that seemed to work ok - http://singularity-hub.org/containers/900

I did add one value to the metadata that is sent so let me update the server with that change and then we can have another testing done!  One sec...

**Comment by vsoch** [comment] 2017-11-21 21:13
@iosonofabio I need to look at yours more closely - it looks like the commits are now included with the payload, and previously this wasn't done (I had a separate function to find all changed recipes). But now there is this new summary with the payload:

```
[{'added': [],
  'author': {'email': 'fabio.zanini@fastmail.fm',
   'name': 'Fabio Zanini',
   'username': 'iosonofabio'},
  'committer': {'email': 'fabio.zanini@fastmail.fm',
   'name': 'Fabio Zanini',
   'username': 'iosonofabio'},
  'distinct': True,
  'id': '3c21aa5596448a4647e0e0396dba4768482a9002',
  'message': 'Works locally',
  'modified': ['Singularity', 'configure_image.sh'],
  'removed': [],
  'timestamp': '2017-11-21T11:45:31-08:00',
  'tree_id': '5de83bb62dfab3440c115451d3d17eae0f198bdd',
  'url': 'https://github.com/iosonofabio/organic-box-factory/commit/3c21aa5596448a4647e0e0396dba4768482a9002'}]
```

**Comment by vsoch** [comment] 2017-11-21 21:36
okay, I figured this out - the Github webhook api is in fact different. I did changes to the code but am going to wait on restarting the server until I have some time to watch it carefully. In the meantime, I've been able to fire off the "stampy" branch, and we can see if that works well. I'm taking a quick run but I'll be able to do the final update later today so that (future) "other branch" builds will work.

**Comment by vsoch** [comment] 2017-11-21 21:43
stampy ftw! http://singularity-hub.org/containers/907

I will post here when the code is updated so this works proper.

**Comment by vsoch** [comment] 2017-11-21 23:41
okay I've updated the code - the next time you commit to the (off branch) we should be able to test. If there are any errors likely I'll get notified, but if you don't hear from me within usually 24 hours please post here again! And if it works, of course feel free to close the issue. Ty!

**Comment by patrickvdb** [comment] 2017-11-22 09:50
It worked for me! Thank you! @iosonofabio?

**Comment by vsoch** [comment] 2017-11-26 15:50
I've closed the issue, please re-open if necessary when you test @iosonofabio. Thanks!

**Closed as completed** 2017-11-26 15:50 UTC
