### ISSUE TITLE
Add support for multi-stage builds

### ISSUE THREAD

**Issue by eburgueno** [singularityhub/singularityhub.github.io#192] opened 2019-10-14 22:35 UTC
## Link to Container Collection Log, Build, or Collection (in that order)

Collection: https://singularity-hub.org/collections/3652
Example Build Log: https://singularity-hub.org/containers/11259/log

### Behavior when Building Locally

Using Singularity 3.2 the build works fine locally
```
$ singularity --version
singularity version 3.2.1-1.el7
```

### Error on Singularity Hub
Relevant context
```
+ Bootstrap: docker
/bin/sh: line 12: Bootstrap:: command not found
ABORT: Aborting with RETVAL=255
```

### What do you think is going on?

The builder bots probably need a newer version of Singularity. Multi-stage builds were [introduced](https://sylabs.io/guides/3.2/user-guide/definition_files.html#multi-stage-builds) in 3.2 (but of course you knew that already :) )

**Comment by vsoch** [comment] 2019-10-14 22:42
You can change the version of your builder in the collection settings. The most recent supported is 3.2.1. 

But you know that already :)

**Comment by eburgueno** [comment] 2019-10-14 22:44
:astonished: I did not! will change that now. Any reason the 3.2 is not the default?

**Comment by vsoch** [comment] 2019-10-14 22:48
That would require me to go back and change the settings for previously set settings. This is out of scope of what I should do as a service provider - for as many users that would want the newer version, there are likely some building containers for older clusters that do not.

**Comment by eburgueno** [comment] 2019-10-14 22:51
You could leave existing settings "as is" and have 3.2 as the default for new ones. But I'm not sure how hard would that be to do, and I agree that other users might have a different expectation.

In any case, my bad, this is not an issue. Thanks for your help, as usual!

**Comment by vsoch** [comment] 2019-10-14 22:56
Sure thing! I'll take a look at the defaults tomorrow.

**Comment by vsoch** [comment] 2019-10-15 11:33
@eburgueno just checked and you're correct - 2.5.1 is set as default, and this is because the 3.2.1 was a new builder and I wanted more feedback before making default. If/when you get to testing, let me know if everything is working okay, and for the next server restart we can make it a default.

**Comment by eburgueno** [comment] 2019-10-21 09:47
@vsoch I am having an issue building with 3.2.1. I tried deleting the collection and creating a new one, but the logs keep showing the same error `[31mFATAL: [0m Unable to create build: mkdir /tmp/sbuild: file exists`

Here's the new [collection](https://singularity-hub.org/collections/3668) and [error log](https://singularity-hub.org/containers/11318/log). I can't see what am I doing wrong. Could you have a look when you get the chance?

**Comment by vsoch** [comment] 2019-10-21 11:38
Could you please turn on debug in the collection settings, and try an otherwise equivalent recipe without multistage build to debug if that is the issue?

**Comment by vsoch** [comment] 2019-10-21 13:04
okay I think I found the issue - the multi stage build (via secure build) in that it needs to have a predictable build path cannot support more than one build, see https://github.com/singularityhub/singularity-python/blob/v3.2.1/singularity/build/scripts/bundle.go#L76. If you want to take a look at the scripts and have an idea for how to support this (based on the logic of [needing to know this path](https://github.com/singularityhub/singularity-python/blob/v3.2.1/singularity/build/scripts/secure-build.sh#L93) then I'd be happy to test this for you! The basic issue is that bundle.go that is compiled with Singularity would need to be able to return the build directory prefix to the secure_build.sh so the bind can happen correctly. Otherwise, your best bet is to not use multistage build.

**Comment by eburgueno** [comment] 2019-10-23 00:49
I had a quick look but I suck and I don't really understand the full logic. In any case, here's a thought: one of of requisites for multi-stage builds is that each stage has a different, unique name. Could `bundle.go` and/or `secure-build.sh` use that (ie: something like `/tmp/sbuild-$STAGE_NAME`)  parsing the recipe file? that way you have a deterministic file path, and the two scripts don't need to talk to each other directly to "discover" it.

**Comment by vsoch** [comment] 2019-10-23 02:34
That’s an interesting idea! And you don’t suck :) is there a surefire, never will fail way to parse the build step names (and determine if they are there in the first place?)

**Comment by eburgueno** [comment] 2019-10-23 06:43
My naive approach would be to `grep` for `'^[[:blank:]]*[Ss]tage:`, but I guess if you're parsing the recipe in Go you might use an API if such a thing is provided with the Singularity codebase. The Stage keyword should only appear in multi-stage build recipes.

**Comment by eburgueno** [comment] 2019-10-23 07:09
I checked the singularity codebase and there seems to be a parser already. `stage` is in the [list of validHeaders](https://github.com/sylabs/singularity/blob/097e8ed884916cc4d810724f7e485b1b35a21f7b/pkg/build/types/parser/deffile.go#L553), maybe this can be reused or invoked somehow? sorry, I can read code but I'm not a programmer so I can't do much else to help.

**Comment by vsoch** [comment] 2019-10-23 13:27
hey it's okay - I think I have minimally something to try! The Sylabs folks mentioned they are going to have another release before SC (Supercomputing) so I can time my work with that. I'll be able to take a look and start testing (worst case) sometime over the weekend.

**Comment by vsoch** [comment] 2019-10-26 16:54
hey @eburgueno I amazingly got this working! Check out:

```bash
singularity pull shub://powerPlant/svaba-srf
singularity shell svaba-srf_latest.sif 

# make sure it's the right recipe
Singularity svaba-srf_latest.sif:/tmp> cat /.singularity.d/Singularity  | grep Stage
Stage: build
Stage: final

# And the file(s) were copied to bin
> /usr/local/bin/svaba 
------------------------------------------------------------
-------- SvABA - SV and indel detection by assembly --------
------------------------------------------------------------
Program: SvABA 
Version: 1.1.3
Contact: Jeremiah Wala [ jeremiah.wala@gmail.org ]
Usage: svaba <command> [options]

Commands:
           run            Run SvABA SV and Indel detection on BAM(s)
           refilter       Refilter the SvABA breakpoints with additional/different criteria to created filtered VCF and breakpoints file.

Report bugs to jwala@broadinstitute.org 
```
The container that originally would not build is now built at

https://singularity-hub.org/collections/3668

You'll notice I updated the builder in your settings to 3.4.2. Could you please test a container build (without multistage) to see if the previous version still works okay?  Once that is confirmed working, then we can close the issue here.

**Comment by eburgueno** [comment] 2019-10-27 08:06
@vsoch you're amazing. I just kicked off a build using no Multi Stage. I'll keep an eye on it.

Also, I believe I made a mistake in my `grep` command above, which I noticed you are using now (yay!). I haven't tested it, but I don't think the `Stage` keyword needs to respect any casing rules. `grep -i` might do the trick instead.

**Comment by eburgueno** [comment] 2019-10-27 11:02
Cool, the good news is that no multi-stage continues to work just fine :tada: 

The other good news is that the keywords are indeed case insensitive, so you might want to adjust your `grep` [here](https://github.com/singularityhub/singularity-python/blob/v3.4.2/singularity/build/scripts/secure-build.sh#L16), otherwise you get `NO STAGES` in the log. Weirdly enough the [build](https://singularity-hub.org/containers/11390/log) worked anyway, thought that might be a different bug :)

**Comment by vsoch** [comment] 2019-10-27 11:13
Great! So we just need to add -i to grep and we’re good? I’ll need to rebuild the entire builder unfortunately, but unlike yesterday that definitely won’t take 4 hours! Another (maybe better?) option would be to leave as is and rebuild when 3.4.3 or 3.5 comes out. Let me know your thoughts!

**Comment by eburgueno** [comment] 2019-10-27 11:22
I don't think you'll see that many Multi Stage builds in the wild (tho hopefully I'm proven wrong about that!). Builds work anyway so I would consider the `grep -i` a cosmetic bug. Happy for that to wait until the next builder.
And thanks again! amazing as usual :1st_place_medal: I'll tidy up my collection after I get some sleep.

**Comment by vsoch** [comment] 2019-10-27 13:25
okay sounds good! Here is what my final thing looks like:

```bash
# Get all stages
CONTENDER_STAGES=$(cat $SINGULARITY_BUILDDEF | grep -i ^[[:blank:]]*Stage:)

# Case 1: We have stages
for stage in $CONTENDER_STAGES; do
    lowerstage=$(echo "$stage" | tr '[:upper:]' '[:lower:]')
    if [ "$lowerstage" != "stage:" ]; then
        stages="$stage $stages"
    fi
done
```
For the above, I tested with an uppercase and lowercase stage, and both ways are checked for all lowercase so we are good. The stages are added backwards so that the last one we loop through is the first, and that's where the final container is built.

> Weirdly enough the build worked anyway, thought that might be a different bug :)

The most important thing is that when the recipe file is parsed (not by me, by Singularity) the build folders are distinct from one another, so this works because Singularity is able to create those folders in /tmp, and then the builder is able to find the final image in the same spot. It just means that my solution is a bit overfit because I'm particular about where I bind to get the final image, which is either the default build folder (not ending in a stage name) or an equivalent folder ending in one. So, it's a rather trivial difference, yes.

I'm going to close the issue (funny it's just morning over here!) have a good rest!

**Closed as completed by vsoch** 2019-10-27 13:25 UTC
