### ISSUE TITLE
Collections not showing

### ISSUE THREAD

**Issue by eburgueno** [singularityhub/singularityhub.github.io#160] opened 2019-02-07 03:09 UTC
### Error on Singularity Hub

Only 500 collections are showing, and searching for other ones does not yield any results (the 'Enter keywords here' just filters the current 500 results).

Searching the collections I manage from the magnifying glass icon seems to work (example: searching `abyss` returns `powerPlant/abyss-srf`), but it would be great if it could also search users so I can share a link to all of the collections I'm creating in a single page. Similar to what [my collections](https://www.singularity-hub.org/u/appiarium#collections) would show. I might open a separate issue for that.

**Comment by vsoch** [comment] 2019-02-07 03:13
That’s not a bug! I filter the main table to 500 because it’s not reasonable to provide them all on one page. You are correct to use the search to find exactly what you are looking for.

**Comment by eburgueno** [comment] 2019-02-07 03:18
Hi @vsoch, love your work! I think it's a bit counter-intuitive to have two search fields.

I understand limiting the results to 500 for performance/practicality, but the criteria as to what shows seems obscure. Maybe limit it to something like "Only showing the 500 most recent successfully built containers"? (or most downloaded/most starred, but I'd rather give exposure to newcomers).

**Comment by vsoch** [comment] 2019-02-07 03:23
It's the latest 500 - I almost removed the collections page entirely but left that for quick browsing of random containers.

If you want to see containers for a particular user, when you are logged in, go to the url that ends with their username (here is mine):

https://www.singularity-hub.org/u/vsoch

At this point my priority for shub is keeping it up and running, as opposed to tweaking tiny details. If there is a staff of software engineers (front end, back end) this might be different, but as one person I don't have the bandwidth given all the projects that are active.

**Comment by vsoch** [comment] 2019-02-07 03:27
I'll write a post to share with the community (and update the docs) to make sure that users know about that particular view. Thanks for the feedback!

**Comment by eburgueno** [comment] 2019-02-07 03:28
> It's the latest 500

Maybe the results are begin cached somewhere, because none of mine show and the list has builds from 2017 (!).

> but as one person I don't have the bandwidth given all the projects that are active

Totally understand! This is a minor thing of course, so I wouldn't bother too much with it. I just thought of reporting it just in case.

**Comment by vsoch** [comment] 2019-02-07 04:38
I think you're right - I need to check on that query! It most definitely isn't the latest, haha. Now I'm wondering...

Let's create a quick list of todo items for the next time I update server certificates, I'll make sure to check on these items:

 - test query to retrieve the latest 500
 - add a note to inform users of what is being shown

and I'll also add to my todo to write a quick tweet / post on the user view (did you get a chance to test it out?)

**Comment by vsoch** [comment] 2019-07-03 16:21
hey @eburgueno a little follow up - I don't see you as a user anymore, so I can't give your profile as an example, but it is possible to share your collection of containers via your profile link. Here is mine:

 - https://www.singularity-hub.org/u/vsoch

For the table, I checked on the current query and the order is based on stars. I think this is a reasonable thing to have (moreso than recent) so I'm going to leave as is for now.

I've also added a message to the collections page that will alert the user of sorting by stars, and only 500 results. It will be updated on the server within the hour.

Since you are no longer a user and I've addressed what we discussed, I'm going to close the issue. Thanks for your feedback!

**Closed as completed by vsoch** 2019-07-03 16:21 UTC

**Comment by vsoch** [comment] 2019-07-03 16:26
Actually I'll likely wait until we don't have so many active users.

**Comment by eburgueno** [comment] 2019-07-03 22:38
hey @vsoch, thank you for the updates. I am still very much an active user, but my collections are published from our bot account, `appiarium`: https://www.singularity-hub.org/u/appiarium

Sorting by stars makes sense, though depending on the popularity of both shub and specific collections you might end up with a relatively static top 500. An possible enhancement would be to let users see the "top starred" vs "latest" vs (say) "most collections" or whatever. In any case, happy with just a description of what I'm seeing :)

> but as one person I don't have the bandwidth given all the projects that are active

I'll chat with you a bit more on this and other semi-related topics on Twitter. Cheers!

**Comment by vsoch** [comment] 2019-07-03 22:44
Ah, that makes sense!
I do use Twitter, but it's not super reliable for keeping a version controlled record of updates (and associating with a milestone) so id you'd like to suggest changes, please open an issue for discussion here. If you want others to chime in, maybe tweet a link to an issue?

**Comment by eburgueno** [comment] 2019-07-03 22:48
@vsoch of course. Will definitely keep shub GitHub issues here on GitHub. I'll just ping you on TW for an unrelated question I have.
