### ISSUE TITLE
warning: underlay of /usr/bin/nvidia-smi required more than 50 bind mounts 

### ISSUE THREAD

**Issue by liuhoward** [singularityhub/singularityhub.github.io#166] opened 2019-04-06 00:15 UTC
Hi, I created a singularity image including cuda, tensorflow etc.
but when I run it PBS script or using shell like singularity --nv shell xxx.img
it always show a warning:
warning: underlay of /usr/bin/nvidia-smi required more than 50 bind mounts

How to fix it?

## Link to Container Collection Log, Build, or Collection (in that order)

[https://www.singularity-hub.org/collections/2604](https://www.singularity-hub.org/collections/2604)

which is just pull a docker image:
[https://hub.docker.com/r/howard15/tensorflow/dockerfile](https://hub.docker.com/r/howard15/tensorflow/dockerfile)

### Behavior when Building Locally

succefully

### Error on Singularity Hub

no error

**Comment by vsoch** [comment] 2019-04-06 00:22
Is there an actual issue or do you just have a warning? if you are running this on a host and using the host libraries (and singularity executable), the issue is likely to stem from that (and not relevant to the build on Singularity Hub). I'd ask the singularity maintainers about the issue itself.

**Comment by liuhoward** [comment] 2019-04-06 17:07
no actual issue, it is just a warning. I can use this image to run my code on GPU.

I modified tensorflow dockerfile from [tensorflow github](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile), here is my [dockerfile](https://github.com/liuhoward/tensorflow_container/blob/master/gpu.Dockerfile), then I create a [Singularity recipe](https://github.com/liuhoward/tensorflow_container/blob/master/Singularity_tensorflow_gpu_py3) to pull my docker image from hub.docker to Singularity-hub, then I pull down singularity img to my local server using  Singularity 2.6.1-dist

**Comment by vsoch** [comment] 2019-04-06 17:09
Alright, so I think since this is a runtime issue, it's something you might want to check with the Singularity board. If it's a warning I wouldn't be concerned, generally. I'm going to close the issue, but please let me know if you want it transferred to sylabs/singularity.

**Closed as completed by vsoch** 2019-04-06 17:09 UTC

**Comment by liuhoward** [comment] 2019-04-07 17:16
no need. thank you very much!
