### ISSUE TITLE
Container Taking a Long Time to Build

### ISSUE THREAD

**Issue by tjhendrickson** [singularityhub/singularityhub.github.io#143] opened 2018-08-13 14:25 UTC
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/1305, tjhendrickson/BIDShcppipelines:v3.27.0

### Error on Singularity Hub

Despite the container currently running it has been running for about a week.

### What do you think is going on?

I have no idea!

**Comment by vsoch** [comment] 2018-08-13 14:32
Sorry is this the right collection? All I see is a successful build --> https://www.singularity-hub.org/collections/1305

**Comment by tjhendrickson** [comment] 2018-08-13 14:39
Well that is the thing, another build is still running, the problem is that
it is that it is taking longer than I think it should. Are there best
practices that I should consider with automated builds?

**Comment by vsoch** [comment] 2018-08-13 14:44
If the container is green, there is no other build running.

**Comment by tjhendrickson** [comment] 2018-08-13 15:13
Trust me I have another build running with a different tag. Could you
please answer my questions?

Timothy Hendrickson
Neuroimaging Analyst/Staff Scientist
University of Minnesota Informatics Institute
University of Minnesota
Bioinformatics M.S. Candidate
Office: 612-624-0783
Mobile: 507-259-3434 (texts okay)

**Comment by vsoch** [comment] 2018-08-13 15:20
I can see it now, it wasn't there before, friend :)

The "best practices" depends on your use case. For example, for repositories that have very frequent changes and commits it would be advisable to do manual builds, and just trigger one when you want to create a tagged release. If you have a Github repository that only merges into master for releases, then it's probably safe / good to have it build from commits (to master, or another branch if your preference). If you are a CI pro and are using continuous integration, then you would do best with a deployment build setting. The different builders are described here --> https://github.com/singularityhub/singularityhub.github.io/wiki#meet-the-builders

So I can't answer your question for the "best practices" because it depends on your use case. If you want to share some of the needs for your containers I can offer to help. You might also want to remove all that personal information from your automated reply, or reply directly on Github so it isn't automatically added from your email :)

**Comment by vsoch** [comment] 2018-08-13 17:09
hey @tjhendrickson ! I can confirm now that the container build gets killed (and isn't able to send a response back to Singularity Hub) so something is up! Could you tell me what you have changed about the build from the previous, and we can start to figure this out? Some possible things:

 - the files you are downloading / extracting are larger than the disk + space needed to build 
 - you remove files in /tmp that are important for the build
 - the build takes over 2 hours

Let me know the above details and we can start to look into this.

**Comment by tjhendrickson** [comment] 2018-08-13 17:24
Hi @vsoch, thank you for updating me on this. 

As far as changes:

I've added some additional dependencies and code in order so an additional piece of the processing pipeline within the container will run, but I do not think I have added enough to the container that would cause it to fail. 

I am not removing files from /tmp within container during the build. 

The build should not take over 2 hours, the other container I built took about one hour.

How would I tell the raw size of the files that I am downloading/extracting into the container?  I can get the container to build locally, and it ends up being ~11GB

P.S. Thanks for the personal information suggestion! Much appreciated.

**Comment by vsoch** [comment] 2018-08-13 17:41
Sure thing! To start, please do a diff between the first and second versions, and then I can see directly the changes that were made.

**Comment by tjhendrickson** [comment] 2018-08-13 19:55
I can definitely do that. As they are both binary files, do you want me to use a particular linux command?

**Comment by vsoch** [comment] 2018-08-13 20:15
Just do a diff (that's the command) on the two different files and that should do the trick! Type man diff to see usage instructions.

another thing I like to do is do a pull request to a little repo that has one file to change the other one and then you see the changes directly in the GitHub interface. No rush - I'm absorbed in something and will be more responsive toward the evening!

**Comment by vsoch** [comment] 2018-10-09 01:39
@tjhendrickson any updates?

**Comment by tjhendrickson** [comment] 2018-10-10 13:41
@vsoch Hey thanks for following up! Yes, I was able to get it to build, but something else is preventing it from building. I'll start another build now and could you perhaps take a look at this one?

**Comment by vsoch** [comment] 2018-10-10 13:44
Sure thing!  I see the builder and I'll shell in and keep an eye on it.

**Comment by vsoch** [comment] 2018-10-10 13:53
okay, files copied into container ok, lots of installs, now it's compiling something. So far so good.

**Comment by vsoch** [comment] 2018-10-10 14:08
This could be a first issue?

```
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Reading package lists...
Post install setup failed
{'d_dir': '/usr/local/fsl', 'test_csv': None, 'verbose': True, 'get_source': None, 'checksum_type': 'sha256', 'checksum': None, 'quiet': True, 'env_all': True, 'update': None, 'skipchecksum': None, 'get_feeds': None, 'requestversion': '5.0.11', 'download': None, 'list_versions': None, 'test_installer': None, 'archive': None, 'env_only': None, 'skip_env': None}
Stage 1
By installing this python distribution you agree to the license terms in
/usr/local/fsl/fslpython/LICENSE.txt
Stage 2
```

**Comment by vsoch** [comment] 2018-10-10 14:09
```
Preparing installation files ...
Installing ...
(Oct 10, 2018 14:02:44) ##################################################################
(Oct 10, 2018 14:02:44) #
(Oct 10, 2018 14:02:44) # Today's Date: 
(Oct 10, 2018 14:02:44) Wed Oct 10 14:02:44 UTC 2018
(Oct 10, 2018 14:02:44) 
(Oct 10, 2018 14:02:44) System Info
(Oct 10, 2018 14:02:44) OS: Linux 4.13.0-1013-gcp
(Oct 10, 2018 14:02:44) Arch: amd64
(Oct 10, 2018 14:02:44) Data Model: 64
(Oct 10, 2018 14:02:44) Language: en
(Oct 10, 2018 14:02:44) Java Vendor: Oracle Corporation
(Oct 10, 2018 14:02:44) Java Home: /tmp/mathworks_5788/sys/java/jre/glnxa64/jre
(Oct 10, 2018 14:02:44) Java Version: 1.7.0_11
(Oct 10, 2018 14:02:44) Java VM Name: Java HotSpot(TM) 64-Bit Server VM
(Oct 10, 2018 14:02:44) Java Class Path: .
(Oct 10, 2018 14:02:44) User Name: root
(Oct 10, 2018 14:02:44) Current Directory: /opt/MCR_v83
(Oct 10, 2018 14:02:44) Input arguments: 
(Oct 10, 2018 14:02:44) root /opt/MCR_v83
(Oct 10, 2018 14:02:44) tmpdir /tmp/mathworks_5788
(Oct 10, 2018 14:02:44) mode silent
(Oct 10, 2018 14:02:44) agreetolicense yes
(Oct 10, 2018 14:02:44) destinationFolder /usr/local/R2014a
(Oct 10, 2018 14:02:44) standalone true
(Oct 10, 2018 14:02:44) connectionMode OFFLINE_ONLY
(Oct 10, 2018 14:02:44) Starting local product/component search
(Oct 10, 2018 14:02:44) Reading /opt/MCR_v83/archives
(Oct 10, 2018 14:02:44) Assembling product list...
(Oct 10, 2018 14:02:44) Reading /opt/MCR_v83
(Oct 10, 2018 14:02:48) Completed local product/component search
(Oct 10, 2018 14:02:48) The destination folder /usr/local/R2014a does not exist.  Would you like to create it?
(Oct 10, 2018 14:02:48) Starting local product/component search
(Oct 10, 2018 14:02:48) Completed local product/component search
(Oct 10, 2018 14:02:48) Installing Product: MATLAB Compiler Runtime 8.3
(Oct 10, 2018 14:03:13) Notes: 
On the target computer, append the following to your LD_LIBRARY_PATH environment variable:

/usr/local/R2014a/v83/runtime/glnxa64:/usr/local/R2014a/v83/bin/glnxa64:/usr/local/R2014a/v83/sys/os/glnxa64:



Next, set the XAPPLRESDIR environment variable to the following value:

/usr/local/R2014a/v83/X11/app-defaults


(Oct 10, 2018 14:03:13) Exiting with status 0
(Oct 10, 2018 14:03:13) End - Successful.
Finished
Ign http://archive.ubuntu.com trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Reading package lists...
Post install setup failed
{'d_dir': '/usr/local/fsl', 'test_csv': None, 'verbose': True, 'get_source': None, 'checksum_type': 'sha256', 'checksum': None, 'quiet': True, 'env_all': True, 'update': None, 'skipchecksum': None, 'get_feeds': None, 'requestversion': '5.0.11', 'download': None, 'list_versions': None, 'test_installer': None, 'archive': None, 'env_only': None, 'skip_env': None}
Stage 1
By installing this python distribution you agree to the license terms in
/usr/local/fsl/fslpython/LICENSE.txt
Stage 2
```

**Comment by vsoch** [comment] 2018-10-10 14:26
okay we are installing again - I'm seeing downloads for freesurfer and other brain software, and this almost has to be what will lead to the issue, but we will see.

**Comment by tjhendrickson** [comment] 2018-10-10 14:32
Okay that's encouraging? Perhaps it got through the fsl step...

**Comment by vsoch** [comment] 2018-10-10 15:04
It just cut for me

```
$ Connection to 35.197.6.41 closed by remote host.
Connection to 35.197.6.41 closed.
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```
So I think the issue is that it did build, but the container (and then the image being pushed to storage, remember we have a sandbox PLUS the image) was greater than the size of the instance.

**Comment by vsoch** [comment] 2018-10-10 15:08
I was able to look at disk space, and during compiling of those final libraries it's already over 51%. So I think the container is too big, unfortunately. The reason it still says running is because the instance basically dies and gets killed. I would suggest a more modular approach to distributing your software, OR as an alternative, have you considered building a docker image and then pulling with Singularity? I think that's what most BIDS images do... eg like:

```
singularity pull docker://...
```
I have to run, I'll be back later in the day if you need more help.

**Comment by vsoch** [comment] 2018-10-10 15:09
The good news is that the container builds fine... he's just fat :)

**Comment by tjhendrickson** [comment] 2018-10-10 15:30
I'll make it more modular. 

Thanks for your help! I'll reach out if I run into issues again.

**Comment by vsoch** [comment] 2018-10-10 16:41
Sounds good! I’m going to keep the issue board modular too, closing here since we figured it out and please ping again if you need help. 🤓

**Closed as completed by vsoch** 2018-10-10 16:41 UTC
