### ISSUE TITLE
Singularity 2.3 builders error when doing a yum bootstrap

### ISSUE THREAD

**Issue by akkornel** [singularityhub/singularityhub.github.io#25] opened 2017-06-14 18:15 UTC
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/1252/log

### Behavior when Building Locally

(In my case, "Locally" means in an Ubuntu 16.10 VM running via Virtual Box on my Mac, using Singularity 2.3)

The build completes successfully!

### Error on Singularity Hub

RPM database is using a weird path: %(bash -c 'echo ~/.rpmdb')

### What do you think is going on?

I'm guessing that the builder is running some form of Ubuntu.  The `yum` and `rpm` packages are likely already installed, but the local RPM configuration is messed up (a problem which was identified during Singularity 2.3's development).

I _think_ the fix is to modify the builder deployment process, so that a file is placed at path `/root/.rpmmacros`, with the following contents:

```
%_var /var
%_dbpath %{_var}/lib/rpm
```

Then the builders would have to be re-deployed.  Or, maybe the builders can be modified in-place?  I'm sorry, I don't know enough about the builders to say for sure.

I say "I _think_", because I don't know how the builders are deployed, and I don't want to sound like an *$*@#($% by saying "Oh, this is **exactly** what you need to do, and how did you not know that already!!!!!  OMG, I can't _believe_ you."  I'm making a small pile of assumptions in this section, and if any of them are wrong, then the problem may be different.

**Comment by vsoch** [comment] 2017-06-15 01:35
hey @akkornel ! Like we talk about, this will go away if you use the docker image for the same OS. If you are worried about version, then you can specify a particular digest (tag or sha digest). I think if your goal is reproducibility, it would be wise to choose a base bootstrap that doesn't have potential errors based on the configuration of the host, which is what we've seen with this kind. I can adjust the builders in a future update to deal with this error, but I think it's actually a good thing that it pops up, because it suggests that this base might not be the best approach. Thanks for the report!

**Comment by vsoch** [comment] 2017-10-09 01:06
ping @cclerget! Does the secure build image handle this use case? It's come up a few times - I remember seeing debootstrap and some other dependencies installed, but am not sure about this particular one!

**Comment by cclerget** [comment] 2017-10-09 04:40
@vsoch Yes https://github.com/cclerget/singularity/blob/d4c5ce80d200505dffc0cbac02772b61470c86f9/libexec/bootstrap-scripts/secbuild.sh#L85

**Comment by vsoch** [comment] 2017-10-09 04:48
awesome! @akkornel I'm going to close the issue here - let's be sure to test when 2.4 is released. Thanks @cclerget you da bomb!

**Closed as completed by vsoch** 2017-10-09 04:48 UTC
