### ISSUE TITLE
Download images for local builds

### ISSUE THREAD

**Issue by standage** [singularityhub/singularityhub.github.io#182] opened 2019-08-08 15:05 UTC
Perhaps I should have asked here first, but I recently posted the following question [on StackOverflow](https://stackoverflow.com/q/57415527/459780).

> I have a system that has no connection to the internet but does have local mirrors of the OS package manager repos, PyPI, Conda, etc. I'd like to build Singularity images on this system. It looks like the [`localimage` bootstrap agent](https://sylabs.io/guides/3.3/user-guide/appendix.html#build-localimage) was designed specifically for this use case, but how would I download the base image from which to build my images? From an internet-connected machine, can I download an image from Singularity Hub in my browser without installing Singularity?

**Comment by vsoch** [comment] 2019-08-08 15:19
Hmm, so your downloads are entirely limited to pypi, and conda? How would you download any general file, or interact with a general API? It seems like your easy option would be to download the bases you'd like elsewhere, and then copy to your server to use for localimage bootstrap. What else did you have in mind?

**Comment by standage** [comment] 2019-08-08 15:22
> It seems like your easy option would be to download the bases you'd like elsewhere, and then copy to your server to use for localimage bootstrap.

Indeed, that's what I had in mind. Thus my question:

> From an internet-connected machine, can I download an image from Singularity Hub in my browser without installing Singularity?

**Comment by standage** [comment] 2019-08-08 15:28
> so your downloads are entirely limited to pypi, and conda?

We do have a few others. But between the OS package manager, the language specific repos (PyPI, CRAN, CPAN, etc), and conda (anaconda, conda-forge, bioconda), it's rare that something important is missing.

> How would you download any general file, or interact with a general API?

We have to download local copies and move them over, in the rare cases this is needed. Calling web APIs is out of the question.

**Comment by vsoch** [comment] 2019-08-08 15:28
Yes, but you'll need to do it programatically because there are strict rules and time limits for accessing the containers. For example, if you look at this page:

https://singularity-hub.org/api/container/haeriamin/singularity-ubuntu:1604

You'll see there is an "image" parameter that gives you the container in storage (you could use wget). However, you couldn't copy paste (or similar) to do this, because the url is a signed URL that is generated on the fly, and is pretty much expired by the time you open the interface and look at it. So what you'd want to do is write a script to get that page (in it's json format) and then grab the image entry and issue wget. That should work in the same time that it would take singularity to do the same. Keep in mind as you are doing this that every container has a weekly get limit, so even just opening the URL linked above (and generating the signed URL) is a count of 1 towards the total.

**Comment by standage** [comment] 2019-08-08 15:48
Awesome, that works!

I noticed that the file in the auto-generated URL has the `.simg` extension. Are all images on Singularity Hub `.simg` files, or are any the new `.sif` format?

**Comment by vsoch** [comment] 2019-08-08 15:53
it totally depends on the version the author of the collection is building - a lot of centers are still in 2.x family, so they would have simg.

**Comment by vsoch** [comment] 2019-08-08 15:53
Or the container could just be old from when that was latest :)

**Comment by vsoch** [comment] 2019-08-08 15:56
You can get images from the Sylabs library too - for example, here is a manifest for busybox:

https://library.sylabs.io/v1/images/busybox:latest

and then download with:

https://library.sylabs.io/v1/imagefile/busybox:latest

The library is maintained by Sylabs (not users like Singularity Hub) so you'll definitely find sif there, along with more consistent base images (I don't provide that on Singularity Hub).

I don't think their API spec is public (I just figured it out) so you didn't hear it from me! :wink:

**Comment by standage** [comment] 2019-08-08 16:02
Got it. I guess I should have read a little more carefully, I had assumed that Singularity Hub hosted both "official" and community images.

In any case, it'll probably be easier to just install Singularity on my home machine, build a base image on that machine, and transfer it over here.

**Comment by standage** [comment] 2019-08-08 16:03
By the way, this was the script I used to download the image.

```python
import json
import requests
import urllib.requests


def download(url, filename):
    response = requests.get(url).json()
    print(json.dumps(response, indent=4))
    urllib.request.urlretrieve(response['image'], filename)

 
download('https://singularity-hub.org/api/container/haeriamin/singularity-ubuntu:1604', './ubuntu1604.simg')
```

Only 355 Mb of the expected 989 Mb downloaded. I'm guessing it timed out, which isn't surprising based on your earlier comments.

**Comment by vsoch** [comment] 2019-08-08 16:07
Thanks for the script! I wouldn't take the time to print anything, just in case. Yes, Singularity Hub is for primarily academic reprodocubility - users connect with GitHub repos to build their containers, and it's less of a library with bases (when I need a base I just use Docker Hub anyway). To get some history, see the FAQ here https://singularityhub.github.io/singularityhub-docs/docs/faq#how-is-singularity-hub-related-to-sylabs-and-singularity I've been running it for over 3 years now, and I'm hoping that Sylabs provides a GitHub integration for reproducible builds, and increases support for science, but it hasn't happened yet. Until then, I'll keep running the shub ship! :)

**Comment by standage** [comment] 2019-08-08 16:33
hashtag applause

**Comment by vsoch** [comment] 2019-08-08 16:34
:rofl: text communication methods are strong, this one! :)

insert yoda gif

**Comment by vsoch** [comment] 2020-05-29 22:06
Closing issue here, nothing to do. If you are interested in deploying your own registry, see https://singularityhub.github.io/sregistry that now has a minio backend for very speedy interactions.

**Closed as completed by vsoch** 2020-05-29 22:06 UTC

**Comment by vsoch** [comment] 2020-05-29 22:07
Also you might be interested in https://github.com/biowdl/singularity-permanent-cache/pull/1, a little library one of the Cromwell folks is putting together to handle downloads that honor the cache and don't require connectivity.
